name: My Actions

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 


      - name: Install dependencies
        run: npm install


      - name: Dime la fecha
        run: date

      - name: Start server
        run: |
          echo "Iniciando el servidor para pruebas..."
          node server.js &
          sleep 
          curl http://localhost:1000 

      - name: Finalizar el workflow
        run: echo "El workflow ha terminado con éxito"
