name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 54.89.241.102 
          username: ec2-user 
          key: ${{ secrets.EC2_SSH_KEY }} 
          port: 22
          script: |
            echo "Conexión a la instancia EC2 exitosa."
            cd ~/Actions-task-and-EC2 
            git pull origin main 
            npm install 
            pm2 stop all || true 
            pm2 start server.js --
